"""
AI-MOS — Alembic Migration Environment Configuration
======================================================
Configures Alembic to use the async SQLAlchemy engine from our
application's settings, enabling `alembic upgrade head` to apply
migrations against the PostgreSQL database.

Key design decisions:
- Database URL is loaded from pydantic-settings (not hardcoded in alembic.ini)
- Uses asyncio.run() for async engine compatibility
- Base.metadata is imported so Alembic can autogenerate future migrations

Usage:
    # Apply all pending migrations:
    alembic upgrade head

    # Roll back one migration:
    alembic downgrade -1

    # Generate a new autogenerated migration (Phase 2+):
    alembic revision --autogenerate -m "add_session_table"
"""

import asyncio
import sys
from logging.config import fileConfig
from pathlib import Path

from alembic import context
from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import create_async_engine

# ---------------------------------------------------------------------------
# Python path adjustment
# Ensures `app` package is importable when running `alembic` from backend/
# ---------------------------------------------------------------------------
# Resolve backend/ directory (parent of app/migrations/)
backend_dir = Path(__file__).resolve().parent.parent.parent
if str(backend_dir) not in sys.path:
    sys.path.insert(0, str(backend_dir))

# Now we can safely import from our app package
from app.core.config import settings  # noqa: E402
from app.core.database import Base  # noqa: E402

# ---------------------------------------------------------------------------
# Alembic Config Object
# ---------------------------------------------------------------------------
config = context.config

# Set the SQLAlchemy URL dynamically from pydantic-settings
# This overrides the blank `sqlalchemy.url =` in alembic.ini
config.set_main_option("sqlalchemy.url", settings.DATABASE_URL)

# Interpret the config file for Python logging
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# ---------------------------------------------------------------------------
# Target metadata for autogenerate support
# When `--autogenerate` is used, Alembic compares Base.metadata to the live DB.
# ---------------------------------------------------------------------------
target_metadata = Base.metadata


# ---------------------------------------------------------------------------
# Offline Migration Mode
# Generates SQL scripts without a live DB connection.
# Run with: alembic upgrade head --sql
# ---------------------------------------------------------------------------
def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode (generates SQL output)."""
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
    )
    with context.begin_transaction():
        context.run_migrations()


# ---------------------------------------------------------------------------
# Online Migration Mode (Async)
# ---------------------------------------------------------------------------
def do_run_migrations(connection: Connection) -> None:
    """Execute migrations synchronously using the provided connection."""
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        compare_type=True,
    )
    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    """Create an async engine and run migrations within a sync context."""
    # NullPool is used for migrations to prevent connection pool issues
    # after migration runs — each migration is a one-shot operation
    connectable = create_async_engine(
        settings.DATABASE_URL,
        poolclass=pool.NullPool,
    )
    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)
    await connectable.dispose()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode against a live database."""
    asyncio.run(run_async_migrations())


# ---------------------------------------------------------------------------
# Entry Point
# ---------------------------------------------------------------------------
if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
